# Generated by Django 4.0 on 2022-08-28 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_images_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='ProductImage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
