# Generated by Django 4.0 on 2022-08-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='modified_date',
        ),
    ]
