# Generated by Django 4.0 on 2022-08-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_img',
            field=models.ImageField(blank=True, upload_to='images/categories'),
        ),
    ]
